;ESTE PROGRAMA NOS MUESTRA EN LOS LEDS CONECTADOS EN PORTB, LA COMPARACIÓN
;DE PORTD (3:0) Y PORTA (RA6:RA3)
;RB2= PA MAYOR PD  RB1 = PA MENOR PD    RB0 = PA IGUAL PD
    #INCLUDE<P18F4550.INC>
    ORG .0
SETTINGS
    CLRF PORTA
    SETF TRISA
    MOVLW H'0F'
    MOVWF ADCON1
    MOVLW H'07'
    MOVWF CMCON
    CLRF PORTB
    CLRF TRISB
    CLRF PORTD
    MOVLW B'00001111'
    MOVWF TRISD
    
COMPARA
    MOVF PORTA,W
    ANDLW B'01111000'
    RRNCF WREG,F
    RRNCF WREG,F
    RRNCF WREG,F
IGUAL
    CPFSEQ PORTD
    GOTO MENOR
    MOVLW H'01'
    MOVWF PORTB
    GOTO COMPARA
MENOR
    CPFSLT PORTD
    GOTO MAYOR
    MOVLW H'02'
    MOVWF PORTB
    GOTO COMPARA
MAYOR
    MOVLW H'04'
    MOVWF PORTB
    GOTO COMPARA
    END