#INCLUDE<P18F4550.INC>
    DATOA EQU .20
    DATOB EQU .25
    VEINTE EQU .20
    SIETE EQU .7
    ANDVALOR EQU .8
    ORVALOR EQU .9
    XORVALOR EQU .10
    SUMMA EQU .6
    RESSTA EQU .27
    PRODUCTO EQU .150
    ORG .0
MAIN
    MOVLW VEINTE
    MOVWF DATOA,1
    MOVLW SIETE
    MOVWF DATOB,1 
AND
    MOVFF DATOA,WREG
    ANDWF DATOB,0,1
    MOVFF WREG,ANDVALOR
OR
    MOVFF DATOA,WREG
    IORWF DATOB,0,1
    MOVFF WREG,ORVALOR
XOR
    MOVFF DATOA,WREG
    XORWF DATOB,0,1
    MOVFF WREG,XORVALOR
SUMAR
    MOVFF DATOA,WREG
    ADDWF DATOB,0,1
    MOVWF SUMMA,1

RESTAR
    MOVFF DATOA,WREG
    SUBWF DATOB,0,1
    MOVWF RESSTA,1

MULTIPLICACION
    MOVFF DATOB,1
    MULWF DATOA,1
    MOVFF PRODL,PRODUCTO
    GOTO MAIN
    END