;Sumador, restador y multiplicador de 2 cantidades de 3 bits
; Ambas cantidades ingresan por portA
; El resultado se visualiza en leds por portb
#include "p18f4550.inc"

#DEFINE DATO H'03' ;PONER ETIQUETAS A CARACTERES, ESTO LEE H'03'
;DATO EQU H'03' ;ESTO LEE SOLO EL 03
#DEFINE QUINCE H'0F'
#DEFINE MASK H'25' ; REGISTRO 37 BANCO 0
#DEFINE SUMANDOUNO H'26' ; REGISTRO 38 BANCO 0
#DEFINE SUMANDODOS H'27' ; REGISTRO 39 BANCO 0

ORG 0
CONFIGURACION
  MOVLW B'01111111'
  MOVWF TRISA,0 ;TRISA=3 POR LO QUE PORTA TIENE -SEEE EEEE
  CLRF PORTA,0 ;MOVLW B'0000000' MOVWF PORTA,0
  MOVLW QUINCE ;W=15
  MOVWF ADCON1,0 ;ADCON1=15 POR LO QUE LAS ENTRADAS DE LOS PUERTOS A,B,E SON DIGITALES
  MOVLW H'07' ;W=07
  MOVWF CMCON,0 ;EL COMPRADOR DEL PORTA A Y E SE APAGA
  CLRF PORTB,0
  MOVLW B'00000000'
  MOVWF TRISB,0 ;TRISB=0, ENTONCES PB=SSSS SSSS
MAIN
  MOVLW B'00001110' ; W=6 que es la máscara que quiero crear
  MOVWF MASK,1 ;MASK=14, aquí oculto el sumando 2, leeré de izquierda a derecha
               ;Por lo tanto, el sumando 1 es el de la izquierda y el segundo es el de la derecha
  MOVFF PORTA,SUMANDOUNO ;PA=W (0||1||2||4)
  MOVF SUMANDOUNO,WREG,0
  ANDWF MASK,W,1 ;Enmascarar a wreg, solo dejé a ra3, RA2 y RA1
  RRNCF SUMANDOUNO,W,0 ;PUEDE SER 0 O W EN DESTINATION
  MOVFF WREG,SUMANDOUNO
  MOVLW B'01110000'
  MOVWF MASK,1 ;aquí oculto el sumando 1
  MOVFF PORTA,SUMANDODOS
  MOVF SUMANDODOS,WREG,0
  ANDWF MASK,W,1 ;Enmascarar a wreg, solo dejé a ra3, RA2 y RA1
  SWAPF SUMANDODOS,W,0 ;PUEDE SER 0 O W EN DESTINATION
  MOVFF SUMANDOUNO,WREG
  SUBWF SUMANDODOS,WREG,1 ;W+DATO=W
  MOVFF WREG,PORTB ;PORTB TIENE EL RESULTADO
  GOTO MAIN
  END