
 ;Programa que enciende un LED con un BOTON en RC4 (bit 4 del PORTC) y apaga el LED que está en RD0 (bit 0 del PORTD)
  ;Usando resistor PULL-UP
    
    
    LIST P=19F4550
    #INCLUDE<P18F4550.INC> 
    
    
    		;CONFIG1L dir 300000h 	20
		;CONFIG	PLLDIV=1	 ; 
		;CONFIG	CPUDIV=OSC1_PLL2 ;CUANDO SE USA XTAL	
		;CONFIG	USBDIV=2

		;CONFIG1H dir 300001h	08
		CONFIG	FOSC=INTOSCIO_EC ;OSCILADOR INTERNO, RA6 COMO PIN, USB USA OSC EC
		CONFIG	FCMEN=OFF        ;DESHABILITDO EL MONITOREO DEL RELOJ
		CONFIG	IESO=OFF

		;CONFIG2L DIR 300002H	38
		CONFIG	PWRT=ON          ;PWRT HABILITADO
		CONFIG  BOR=OFF		 ;BROWN OUT RESET DESHABILITADO
		CONFIG BORV=3		 ;RESET AL MINIMO VOLTAJE NO UTILZADO EN ESTE CASO
		CONFIG	VREGEN=ON	 ;REULADOR DE USB ENCENDIDO

		;CONFIG2H DIR 300003H	1E
		CONFIG	WDT=OFF          ;WACH DOG DESHABILITADO
		CONFIG WDTPS=32768      ;TIMER DEL WATCHDOG 
		
		;CONFIG3H DIR 300005H	81
		CONFIG	CCP2MX=ON	 ;CCP2 MULTIPLEXADAS CON RC1	
		CONFIG	PBADEN=OFF       ;PUERTO B PINES DEL 0 AL 4 ENTRADAS DIGITALES
		CONFIG  LPT1OSC=OFF	 ;TIMER1 CONFIURADO PARA OPERAR EN BAJA POTENCIA
		CONFIG	MCLRE=ON         ;MASTER CLEAR HABILITADO
		
		;CONFIG4L DIR 300006H	81
		CONFIG	STVREN=ON	 ;SI EL STACK SE LLENA CAUSE RESET		
		CONFIG	LVP=OFF		 ;PROGRAMACIÒN EN BAJO VOLTAJE APAGADO
		CONFIG	ICPRT=OFF	 ;REGISTRO ICPORT DESHABILITADO
		CONFIG	XINST=OFF	 ;SET DE EXTENCION DE INSTRUCCIONES Y DIRECCIONAMIENTO INDEXADO DESHABILITADO

		;CONFIG5L DIR 300008H	0F
		CONFIG	CP0=OFF		 ;LOS BLOQUES DEL CÒDIGO DE PROGRAMA
		CONFIG	CP1=OFF          ;NO ESTAN PROTEGIDOS
		CONFIG	CP2=OFF		 
		CONFIG	CP3=OFF
		
		;CONFIG5H DR 300009H	C0
		CONFIG	CPB=OFF		 ;SECTOR BOOT NO ESTA PROTEGIDO
		CONFIG	CPD=OFF		 ;EEPROM N PROTEGIDA

		;CONFIG6L DIR 30000AH	0F
		CONFIG	 WRT0=OFF	 ;BLOQUES NO PROTEGIDOS CONTRA ESCRITURA
		CONFIG	 WRT1=OFF
		CONFIG	 WRT2=OFF
		CONFIG	 WRT3=OFF

		;CONFIG6H DIR 30000BH	E0
		CONFIG	 WRTC=OFF	 ;CONFIGURACION DE REGISTROS NO PROTEGIDO
		CONFIG	 WRTB=OFF	 ;BLOQUE BOOTEBLE NO PROTEGIDO
		CONFIG	 WRTD=OFF	 ;EEPROMDE DATOS NO PROTGIDA

		;CONFIG7L DIR 30000CH	0F
		CONFIG	 EBTR0=OFF	 ;TABLAS DE LETURA NO PROTEGIDAS
		CONFIG	 EBTR1=OFF
		CONFIG	 EBTR2=OFF
		CONFIG	 EBTR3=OFF

		;CONFIG7H DIR 30000DH	40
		CONFIG	 EBTRB=OFF	 ;TABLAS NO PROTEGIDAS	
    
    
    
    #DEFINE LED PORTD,0,0 ;Definimos al bit 0 del PORTD como la salida del LED
    #DEFINE BOTON PORTB,4,0 ;Definimos al bit 4 del PORTB como la entrada del btn
    
    ORG .0
    
    INICIO
    
	CLRF PORTD,0 ;Limpiamos PORTD
	CLRF PORTB,0 ;Limpiamos PORTB
	BSF TRISB,4,0 ;Definimos como salida el bit 4 del PORTD
	CLRF TRISD,0 ;Definimos como entrada el PORTD
	MOVLW B'11000111' ;Establecemos la CON-figuracion del Timer0 (T0CON), el num. 215 lo pasamos a W
	MOVWF T0CON,0 
	; bit 7: Enciende el timer
	; bit 6: Timer de 8 bits
	; bit 5: reloj interno
	; bit 4: flanco de subida (si es que tiene cont. de eventos)
	; bit 3: con preescaler
	; bit 2,1,0: preescaler 1:256
	
	
    MAIN
	BTFSC BOTON  ;Si el botón está presionándose
	GOTO MAIN
	;BTG LED ;BTG AQUI ES PRESS
    ESPERA 
	CALL DELAY
	BTFSS BOTON  ;Si el botón ya se soltó
	GOTO ESPERA
	BTG LED ;BTG AQUI ES PULL
	GOTO MAIN
    DELAY
	CLRF TMR0L ;Limpiamos al registro LOW de Timer 0
	MOVLW .10 ;Retardo de 10 ms
    ASK
	CPFSEQ TMR0L,0 ;Comparamos aL Timer 0 con W, y saltamos hasta que sea igual
	GOTO ASK
	RETURN 
END

