 ;PROGRAMADOR: FALC�N CAMPOS JORGE ANTONIO 
 ;PROGRAMA QUE SIMULA UNA SERIE DE LUCES CON LEDS

LIST P=18F4450
#INCLUDE<P18F4550.INC>

 
 		;CONFIG1L dir 300000h 	20
		;CONFIG	PLLDIV=1	 ; 
		;CONFIG	CPUDIV=OSC1_PLL2 ;CUANDO SE USA XTAL	
		;CONFIG	USBDIV=2

		;CONFIG1H dir 300001h	08
		CONFIG	FOSC=INTOSCIO_EC ;OSCILADOR INTERNO, RA6 COMO PIN, USB USA OSC EC
		CONFIG	FCMEN=OFF        ;DESHABILITDO EL MONITOREO DEL RELOJ
		CONFIG	IESO=OFF

		;CONFIG2L DIR 300002H	38
		CONFIG	PWRT=ON          ;PWRT HABILITADO
		CONFIG  BOR=OFF		 ;BROWN OUT RESET DESHABILITADO
		CONFIG BORV=3		 ;RESET AL MINIMO VOLTAJE NO UTILZADO EN ESTE CASO
		CONFIG	VREGEN=ON	 ;REULADOR DE USB ENCENDIDO

		;CONFIG2H DIR 300003H	1E
		CONFIG	WDT=OFF          ;WACH DOG DESHABILITADO
		CONFIG WDTPS=32768      ;TIMER DEL WATCHDOG 
		
		;CONFIG3H DIR 300005H	81
		CONFIG	CCP2MX=ON	 ;CCP2 MULTIPLEXADAS CON RC1	
		CONFIG	PBADEN=OFF       ;PUERTO B PINES DEL 0 AL 4 ENTRADAS DIGITALES
		CONFIG  LPT1OSC=OFF	 ;TIMER1 CONFIURADO PARA OPERAR EN BAJA POTENCIA
		CONFIG	MCLRE=ON         ;MASTER CLEAR HABILITADO
		
		;CONFIG4L DIR 300006H	81
		CONFIG	STVREN=ON	 ;SI EL STACK SE LLENA CAUSE RESET		
		CONFIG	LVP=OFF		 ;PROGRAMACI�N EN BAJO VOLTAJE APAGADO
		CONFIG	ICPRT=OFF	 ;REGISTRO ICPORT DESHABILITADO
		CONFIG	XINST=OFF	 ;SET DE EXTENCION DE INSTRUCCIONES Y DIRECCIONAMIENTO INDEXADO DESHABILITADO

		;CONFIG5L DIR 300008H	0F
		CONFIG	CP0=OFF		 ;LOS BLOQUES DEL C�DIGO DE PROGRAMA
		CONFIG	CP1=OFF          ;NO ESTAN PROTEGIDOS
		CONFIG	CP2=OFF		 
		CONFIG	CP3=OFF
		
		;CONFIG5H DR 300009H	C0
		CONFIG	CPB=OFF		 ;SECTOR BOOT NO ESTA PROTEGIDO
		CONFIG	CPD=OFF		 ;EEPROM N PROTEGIDA

		;CONFIG6L DIR 30000AH	0F
		CONFIG	 WRT0=OFF	 ;BLOQUES NO PROTEGIDOS CONTRA ESCRITURA
		CONFIG	 WRT1=OFF
		CONFIG	 WRT2=OFF
		CONFIG	 WRT3=OFF

		;CONFIG6H DIR 30000BH	E0
		CONFIG	 WRTC=OFF	 ;CONFIGURACION DE REGISTROS NO PROTEGIDO
		CONFIG	 WRTB=OFF	 ;BLOQUE BOOTEBLE NO PROTEGIDO
		CONFIG	 WRTD=OFF	 ;EEPROMDE DATOS NO PROTGIDA

		;CONFIG7L DIR 30000CH	0F
		CONFIG	 EBTR0=OFF	 ;TABLAS DE LETURA NO PROTEGIDAS
		CONFIG	 EBTR1=OFF
		CONFIG	 EBTR2=OFF
		CONFIG	 EBTR3=OFF

		;CONFIG7H DIR 30000DH	40
		CONFIG	 EBTRB=OFF	 ;TABLAS NO PROTEGIDAS	
 
 
 
ORG D'0'

CLRF PORTB ;Limpiamos PORTD, el puerto a utilizar
CLRF TRISB ;Limpiamos de nuevo PORTD usando TRISD para definirlo como OUT

CLRF PORTC
CLRF TRISC
		
MOVLW B'11010111' ;Movemos a el num. 199 a W
MOVWF T0CON ;Movemos de W a T0CON el num. 199, que hace lo siguiente:  
    ;Enciende el timer, timer de 8 bits, reloj interno, flanco de bajada (si tiene cont. de eventos), sin preescaler, preescaler 1:256

 
MAIN
    
    MOVLW B'10000000'
    MOVWF PORTC 
    CALL DELAY 
    
    MOVLW B'01000000'
    MOVWF PORTC 
    CALL DELAY 
    
    MOVLW B'10000000' ;Bit 7 encendido, lo pasamos a W
    MOVWF PORTB ;Movemos el bit 7 encendido de W a PORTD
    CALL DELAY ;Lllamamos al retardo
   
    MOVLW B'01000000'
    MOVWF PORTB
    CALL DELAY
    
    MOVLW B'00100000'
    MOVWF PORTB
    CALL DELAY
    
    MOVLW B'00010000'
    MOVWF PORTB
    CALL DELAY
     
    MOVLW B'000010000'
    MOVWF PORTB
    CALL DELAY
   
    MOVLW B'000001000'
    MOVWF PORTB
    CALL DELAY
    
    MOVLW B'000000100'
    MOVWF PORTB
    CALL DELAY
    
    MOVLW B'000000010'
    MOVWF PORTB
    CALL DELAY

    MOVLW B'00000001'
    MOVWF PORTB
    CALL DELAY

    MOVLW B'00000000'
    MOVWF PORTB
    CALL DELAY

   
    
    
DELAY 
    CLRF TMR0L ;Limpiamos el registro TMR0L 
    MOVLW D'50' ;Movemos el num. 50 a W
    
COMP
    CPFSEQ TMR0L ;Compara si lo que est� en TRM0L es igual a lo que est� en W
    BRA COMP
    RETURN
    
END