; Un switch controla el encedido o apagado de un led
#include "p18f4550.inc"

ORG 0

CONFIGURACION
  MOVLW B'00000001'
  MOVWF TRISA,0 
  CLRF PORTA,0 ;MOVLW B'0000000' MOVWF PORTA,0
  MOVLW QUINCE ;W=15
  MOVWF ADCON1,0 ;ADCON1=15 POR LO QUE LAS ENTRADAS DE LOS PUERTOS A,B,E SON DIGITALES
  MOVLW H'07' ;W=07
  MOVWF CMCON,0 ;EL COMPRADOR DEL PORTA A Y E SE APAGA

MAIN
  BTFSS PORTA,0.0
  GOTO ISOFF
  GOTO ISON

ISOFF
  BCF PORTA,0,0
  GOTO MAIN
ISON
  BSF PORTA,0,0
  GOTO MAIN