#INCLUDE "p18F4550.inc"
SUMANDO EQU 0X1F
TAREA EQU 0X79
TAREADOS EQU 0X07
CONSTWREG EQU MOVLW 0X07
ORG 0

MAIN
  ;MOVL 0X4D
  ;ADDLW SUMANDO
  CONSTWREG
  SUBLW TAREA ;RESTA
  CONSTWREG
  XORLW TAREA ;XOR
  CONSTWREG
  IORLW TAREA ;OR
  CONSTWREG
  ANDLW TAREA ;AND
  ; NOt de ambas cantidades, suma, resta multiplicación
  COMF TAREA ;NOT
  COMF TAREADOS
  

  
  GOTO MAIN
  END
