;Realizar la suma (PA(RA1, RA0)) + (DATO(15)) y el resultado se guarda en suma
#include "p18f4550.inc"

#DEFINE DATO H'03' ;PONER ETIQUETAS A CARACTERES, ESTO LEE H'03'
;DATO EQU H'03' ;ESTO LEE SOLO EL 03
#DEFINE QUINCE H'0F'
#DEFINE SUMA H'225' ;BANCO 2 REGISTRO 37

ORG 0
CONFIGURACION
  MOVLW B'0000011'
  MOVWF TRISA,0 ;TRISA=3 POR LO QUE PORTA TIENE -SSSSSSEE
  CLRF PORTA,0 ;MOVLW B'0000000' MOVWF PORTA,0
  MOVLW QUINCE ;W=15
  MOVWF ADCON1,0 ;ADCON1=15 POR LO QUE LAS ENTRADAS DE LOS PUERTOS A,B,E SON DIGITALES
  MOVLW H'07' ;W=07
  MOVWF CMCON,0 ;EL COMPRADOR DEL PORTA A Y E SE APAGA
  CLRF PORTB,0
  MOVLW B'00000000'
  MOVWF TRISB,0 ;TRISB=0, ENTONCES PB=SSSS SSSS
MAIN
  MOVLW QUINCE ;W=15
  MOVWF DATO,1
  MOVF PORTA,W,0 ;PA=W (0||1||2||4)
  ADDWF DATO,W,1 ;W+DATO=W
  MOVFF WREG,PORTB ;PORTB TIENE EL RESULTADO
  GOTO MAIN
  END

