#INCLUDE "p18F4550.inc"
SUMANDO EQU 0X1F
TAREA EQU 0X79
TAREADOS EQU 0X07
CONSTWREG EQU MOVLW 0X07
ORG 0

MAIN
  ; NOt de ambas cantidades, suma, resta multiplicación
  COMF TAREA ;NOT
  COMF TAREADOS
  MOVL TAREA
  MULLW TAREADOS
  ADDLW TAREADOS
  SUBLW TAREADOS
  
  GOTO MAIN
  END
