
    #include "p18f4550.inc"

SUMANDO EQU 0X1F
TAREA EQU 0X79
TAREADOS EQU 0X07
    ORG 0

MAIN
  ; NOt de ambas cantidades, suma, resta multiplicación
  MOVLW TAREA
  ;NOT ambas
    COMF TAREA
    COMF TAREADOS
  ;MULTIPLICACION
    MOVLW TAREA
    MULLW TAREADOS
  ;SUMAR
    MOVLW TAREA
    ADDLW TAREADOS
  ;RESTAR mayor de menor
    MOVLW TAREA
    SUBLW TAREADOS
  ;RESTAR menor de mayor
    MOVLW TAREADOS
    SUBLW TAREA
  GOTO MAIN
  END