#INCLUDE "p18F4550.inc"
SUMANDO EQU 0X1F
TAREA EQU 0X79
TAREADOS EQU 0X07
CONSTWREG EQU MOVLW 0X07
ORG 0

MAIN
  ; NOt de ambas cantidades, suma, resta multiplicación
  MOVLW TAREA
  NOTAMBAS
    COMF TAREA
    COMF TAREADOS
  MULTIPLICACION
    MOVLW TAREA
    MULLW TAREADOS
  SUMAR
    MOVLW TAREA
    ADDLW TAREADOS
  RESTARMAYORMENOR
    MOVLW TAREA
    SUBLW TAREADOS
  RESTARMENORMAYOR
    MOVLW TAREADOS
    SUBLW TAREA
  GOTO MAIN
  END
